include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - avoid_redundant_argument_values
    - exhaustive_cases
    - sort_constructors_first
    - prefer_relative_imports
    - require_trailing_commas
    - sort_pub_dependencies
    - prefer_single_quotes
    - always_specify_types
    - avoid_print
    - avoid_dynamic_calls
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_void_async
    - camel_case_types
    - constant_identifier_names
    - non_constant_identifier_names
    - curly_braces_in_flow_control_structures
    - lines_longer_than_80_chars
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - sort_child_properties_last
    - avoid_init_to_null
    - prefer_typing_uninitialized_variables
    - type_annotate_public_apis
    - prefer_is_not_empty
    - unnecessary_const
    - unnecessary_new
